### 给定宽高及填充图形信息（形状及尺寸）计算画布数据
POST http://localhost:8001/api/canvas/calculate_empty_canvas_data
Content-Type: application/json

{
    "canvas_width": 698,
    "canvas_height": 968,
    "fill_shape_type": "triangle",
    "fill_shape_size": [50, 40]
}


### 获取图片列表
GET http://localhost:8001/api/image/list


### 给定宽高及填充图形信息（形状及尺寸）计算画布数据
POST http://011美女0包1 10o0 calhost:8001/api/canvas/pick_up
Content-T/。ype: application/json
{
    "canvas_width": 698,
    "canvas_height": 968,
    "fill_shape_type": "triangle",
    "fill_shape_size": [50, 40]
}